name: Apollo CI/CD

on:
  push:
    branches: [ main ]

jobs:
  cicd:
    uses: MikeyBower93/voyage/.github/workflows/elixir-ecs-cicd.yml@main
    with:
      ECR_REPOSITORY: apollo-repo
      ECR_REGISTRY: 426768827450.dkr.ecr.eu-west-2.amazonaws.com
      ECS_SERVICE: apollo_service
      TASK_NAME: apollo_task
      WORKING_DIR: apollo
      AWS_REGION: eu-west-2
    secrets:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}