name: React S3 CI/CD

on:
  workflow_call:
    inputs:
      AWS_BUCKET:
        required: true
        type: string
      WORKING_DIR:
        required: true
        type: string 
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm run build
        working-directory: ${{ inputs.WORKING_DIR }}
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ inputs.AWS_BUCKET }}
          source_dir: '${{ inputs.WORKING_DIR }}/build'